# Netlify build settings
[build]
  publish = "."
  command = "echo 'Static site - no build command needed'"

# Form processing settings - DISABLED to prevent CSS/JS issues
[build.processing]
  skip_processing = true

# Security and performance headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirects for admin panel and SPA behavior
[[redirects]]
  from = "/admin/*"
  to   = "/admin/index.html"
  status = 200